<?php
/* @generated by Application Composer frdl/webfan */
/* include this on top of every project or entry point @using @$this ! */
require_once __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'inc'.DIRECTORY_SEPARATOR.'O.php';
require_once __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'inc'.DIRECTORY_SEPARATOR.'A.php';
require_once __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'inc'.DIRECTORY_SEPARATOR.'App.php';
require_once __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'inc'.DIRECTORY_SEPARATOR.'Stream.php';
require_once __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'inc'.DIRECTORY_SEPARATOR.'Loader.php';
require_once __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'inc'.DIRECTORY_SEPARATOR.'SourceLoader.php';
require_once __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'inc'.DIRECTORY_SEPARATOR.'Autoloader.php';

\frdl\webfan\Autoloading\SourceLoader::repository('frdl'); 

\frdl\webfan\App::God(true, 'frdl\webfan\Autoloading\Autoloader','AC boot') 

;



  \frdl\webfan\Autoloading\SourceLoader::top()
  
   ->addPsr4('frdlweb\\', __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR, false)  
   -> class_mapping_add('AltoRouter', __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'vendor'.DIRECTORY_SEPARATOR.'AltoRouter-master'.DIRECTORY_SEPARATOR.'AltoRouter.php')
   ->addPsr4('frdl\\', __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'vendor'.DIRECTORY_SEPARATOR.'webfan-master'.DIRECTORY_SEPARATOR.'.ApplicationComposer'.DIRECTORY_SEPARATOR.'lib'.DIRECTORY_SEPARATOR.'frdl'.DIRECTORY_SEPARATOR, false)  	  
   
       
;